name: Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker-vault-cli container
        run: docker build -t docker-vault-cli .

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag docker-vault-cli quay.io/mynth/docker-vault-cli:$TAG
          docker tag docker-vault-cli quay.io/mynth/docker-vault-cli:latest
          docker push quay.io/mynth/docker-vault-cli:$TAG
          docker push quay.io/mynth/docker-vault-cli:latest
        if: github.ref == 'refs/heads/main'

  publish-arm:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker-vault-cli container
        run: docker build --platform linux/arm64 -t docker-vault-cli .

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag docker-vault-cli quay.io/mynth/docker-vault-cli:arm-$TAG
          docker tag docker-vault-cli quay.io/mynth/docker-vault-cli:arm-latest
          docker push quay.io/mynth/docker-vault-cli:arm-$TAG
          docker push quay.io/mynth/docker-vault-cli:arm-latest
        if: github.ref == 'refs/heads/main'

  publish-python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker-vault-cli container
        run: docker build -f Python.dockerfile -t docker-vault-cli .

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag docker-vault-cli quay.io/mynth/docker-vault-cli:python-$TAG
          docker tag docker-vault-cli quay.io/mynth/docker-vault-cli:python
          docker push quay.io/mynth/docker-vault-cli:python-$TAG
          docker push quay.io/mynth/docker-vault-cli:python
        if: github.ref == 'refs/heads/main'
